jobs:
  - job: build
    displayName: Build AspSecurityHeaders NuGet Package
    steps:
      - template: ../steps/setup_sdk.yml
      - task: DotNetCoreCLI@2
        displayName: Restore packages
        inputs:
          command: restore
          restoreArguments: --locked-mode
          workingDirectory: AspSecurityHeaders
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: build
          arguments: --no-restore
          workingDirectory: AspSecurityHeaders
      - task: DotNetCoreCLI@2
        displayName: Create NuGet package
        inputs:
          command: pack
          arguments: --no-restore
          workingDirectory: AspSecurityHeaders
      - publish: $(Build.ArtifactStagingDirectory)
        artifact: packages
        displayName: Upload nupkg artifact
