jobs:
  - job: test
    displayName: Test AspSecurityHeaders
    dependsOn:
      - build

    strategy:
      matrix:
        linux_6:
          imageName: ubuntu-latest
          dotnetVersion: 6.x
        mac_6:
          imageName: macOS-latest
          dotnetVersion: 6.x
        windows_6:
          imageName: windows-latest
          dotnetVersion: 6.x

    pool:
      name: Azure Pipelines
      vmImage: $(imageName)

    steps:
      - task: UseDotNet@2
        displayName: Use .NET Core $(dotnetVersion)
        inputs:
          packageType: sdk
          version: $(dotnetVersion)
      - task: DotNetCoreCLI@2
        displayName: Restore packages
        inputs:
          command: restore
          restoreArguments: --locked-mode
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: build
      - task: DotNetCoreCLI@2
        displayName: Test
        inputs:
          command: test
          workingDirectory: AspSecurityHeaders.Test
