jobs:
  - job: test
    displayName: Test AspSecurityHeaders
    dependsOn:
      - build

    strategy:
      matrix:
        linux:
          imageName: ubuntu-latest
        mac:
          imageName: macOS-latest
        windows:
          imageName: windows-latest

    pool:
      name: Azure Pipelines
      vmImage: $(imageName)

    steps:
      - template: ../steps/setup_sdk.yml
      - task: DotNetCoreCLI@2
        displayName: Restore packages
        inputs:
          command: restore
          restoreArguments: --locked-mode
      - task: DotNetCoreCLI@2
        displayName: Build
        inputs:
          command: build
          arguments: --no-restore
      - task: DotNetCoreCLI@2
        displayName: Test
        inputs:
          command: test
          workingDirectory: AspSecurityHeaders.Test
          arguments: --no-restore
          testRunTitle: AspSecurityHeaders.Test_$(imageName)
