pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest

trigger:
  branches:
    include:
      - main

stages:
  - stage: build_stage
    displayName: Build and Test
    jobs:
      - template: jobs/build.yml
      - template: jobs/test.yml
