name: CI-Pipeline

on:
  workflow_dispatch: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build NuGet package
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x
      - uses: actions/checkout@v2
      - name: Restore packages
        run: dotnet restore --locked-mode
        working-directory: AspSecurityHeaders
      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: AspSecurityHeaders
      - name: Create NuGet package
        run: dotnet pack --no-restore --no-build --configuration Release
        working-directory: AspSecurityHeaders
      - uses: actions/upload-artifact@v2
        with:
          name: AspSecurityHeaders.nupkg
          path: AspSecurityHeaders/bin/Release/*.nupkg
          if-no-files-found: error

  test:
    name: Run Tests
    needs: 
      - build
    strategy:
      fail-fast: false
      matrix: 
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        framework:
          - net5.0
          - net6.0
          - netcoreapp3.1
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x
      - uses: actions/checkout@v2
      - name: Restore packages
        run: dotnet restore --locked-mode
        working-directory: AspSecurityHeaders.Test
      - name: Build
        run: dotnet build --no-restore --framework ${{ matrix.framework }}
        working-directory: AspSecurityHeaders.Test
      - name: Run tests
        run: dotnet test --no-restore --no-build --framework ${{ matrix.framework }}
        working-directory: AspSecurityHeaders.Test