name: Dependabot PR fixup

on:
  pull_request:
    branches:
      -  dependabot/nuget/* 
        
jobs: 
  pr_fixup:
    name: PR Fixup
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.0.x
            6.0.x
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          persist-credentials: true
      - name: Update lockfiles
        run: dotnet restore --use-lock-file
      - name: Update pull request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Fixup NuGet lockfiles
          branch: ${{ github.ref }}
          delete-branch: true