name: Dependabot PR fixup

on:
  workflow_dispatch: 
  pull_request:
    branches: 
      - main
    types:
      - opened
      - synchronize

jobs: 
  pr_fixup:
    name: PR Fixup
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.0.x
            6.0.x
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          persist-credentials: true
      - name: Update lockfiles
        run: dotnet restore --use-lock-file
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update lockfiles
          
  pr_automerge:
    name: Enable Automerge
    needs:
      - pr_fixup
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Fetch dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable auto-merge
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}