name: Update dependencies

on:
  schedule:
    - cron: '5 4 * * 2'
  workflow_dispatch: 
    
jobs: 
  update_packages:
    name: Update packages
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            3.1.x
            6.0.x
      - name: Install dotnet outdated tool
        run: dotnet tool install --global dotnet-outdated-tool
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Restore packages
        run: dotnet restore --locked-mode
      - name: List outdated package
        run: dotnet outdated
      - name: Upgrade outdated package
        run: dotnet outdated --upgrade --transitive
      - name: Show changes
        run: git diff
        